name: Build and Push Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./app
          file: ./Dockerfile
          platforms: linux/amd64
          tags: manimahesh/streamlit:latest
          secrets: |
            "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"