name: Build and Push Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: checkout
        uses: actions/checkout@v4

      - 
        name: build image
        run: docker build ./app -t manimahesh/streamlit:latest

      - 
        name: push image
        run: docker push manimahesh/streamlit:latest