name: Build and Push Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Read Secrets
        run: echo "Docker Username secrets: ${{ secrets.DOCKERHUB_USERNAME }}"
        run: echo "Docker Username env: ${{ env.DOCKERHUB_USERNAME }}"
        run: echo "Docker Username vars: ${{ vars.DOCKERHUB_USERNAME }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: checkout
        uses: actions/checkout@v4

      - 
        name: build image
        run: docker build --secret id=OPENAI_API_KEY, env=${{ secrets.OPENAI_API_KEY }} ./app -t manimahesh/streamlit:latest

      - 
        name: push image
        run: docker push manimahesh/streamlit:latest